### ISSUE TITLE
Add parameter to force `verify_certs=False` on GLPI()

### ISSUE THREAD

**Issue by mathieumd** [unistra/ansible-collection-glpi#4]
One of our GLPI is internal only, and we set it up with a self-signed TLS certificate.

It would be nice if you could add a configuration parameter `glpi_verify_certs` to disable certificate checking.

For now, I modified `ansible_collections/unistra/glpi/plugins/inventory/inv.py` at line 103 to add `, verify_certs=False`:
```python
            self.glpi = GLPI(url=str(glpi_url), apptoken=str(glpi_apptoken), auth=str(glpi_auth), verify_certs=False)
```

**Comment by fmenabe** [comment]
I added the parameters to disable certificate checking (`glpi_verify_certs`) and to manage how authentication parameters are passed to the API (`glpi_use_headers`; cf unistra/python-glpi-api#5).

**Comment by mathieumd** [comment]
Thank you!!
